apiVersion: v2
appVersion: "1.59.1"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 12.12.2
  - condition: redis.enabled
    name: redis
    repository: https://deps.truecharts.org
    version: 6.0.51
description: High performance self-hosted photo and video backup solution.
home: https://truecharts.org/charts/stable/immich
icon: https://truecharts.org/img/hotlink-ok/chart-icons/immich.png
keywords:
  - photos
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: immich
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/immich
  - https://github.com/immich-app/immich
version: 7.0.10
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
